# Generated by Django 5.0.2 on 2024-04-01 10:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('course_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Speakers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('speaker_name', models.CharField(max_length=20)),
                ('speaker_img', models.ImageField(upload_to='speakers_img')),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_name', models.CharField(max_length=100)),
                ('event_description', models.TextField()),
                ('event_date', models.DateField()),
                ('event_time', models.TimeField()),
                ('event_price', models.IntegerField()),
                ('event_learning_credits', models.IntegerField(default=None)),
                ('event_lifetime_learners', models.IntegerField(default=None)),
                ('event_rating', models.FloatField(max_length=20)),
                ('event_first_published', models.DateField()),
                ('event_num_ratings', models.IntegerField()),
                ('event_times_launched', models.IntegerField()),
                ('event_num_interested', models.IntegerField()),
                ('event_num_hours', models.IntegerField()),
                ('event_num_days', models.IntegerField()),
                ('event_skills', models.CharField(max_length=200)),
                ('more_about_event', models.TextField()),
                ('event_relevance_of_program', models.TextField()),
                ('event_recommended_learners', models.TextField()),
                ('event_what_will_learn', models.TextField()),
                ('event_img', models.ImageField(upload_to='event_pics')),
                ('event_authors', models.ManyToManyField(default=None, related_name='events', to='course_app.authors')),
                ('event_collab', models.ManyToManyField(default=None, related_name='events', to='course_app.collaborators')),
                ('event_location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course_app.location')),
                ('event_medium_of_communication', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course_app.language')),
                ('event_mode', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='course_app.mode')),
                ('event_producers', models.ManyToManyField(default=None, related_name='events', to='course_app.producers')),
                ('event_sponsors', models.ManyToManyField(default=None, related_name='events', to='course_app.sponsors')),
                ('event_topic', models.ManyToManyField(default=None, related_name='events', to='course_app.topics')),
            ],
        ),
    ]
