# Generated by Django 5.0.3 on 2024-05-23 06:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course_app', '0001_initial'),
        ('credentials', '0002_interest_purpose_user_detail'),
        ('event_app', '0002_remove_event_event_topic'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='course_topic',
        ),
        migrations.AddField(
            model_name='course',
            name='course_educators',
            field=models.ManyToManyField(blank=True, default=None, related_name='current_educators', to='course_app.educators'),
        ),
        migrations.AddField(
            model_name='course',
            name='course_interest',
            field=models.ManyToManyField(default=None, related_name='courses', to='credentials.interest'),
        ),
        migrations.AddField(
            model_name='course',
            name='course_past_educators',
            field=models.ManyToManyField(blank=True, default=None, related_name='past_educators', to='course_app.educators'),
        ),
        migrations.AddField(
            model_name='course',
            name='course_stage',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='course_app.stage'),
        ),
        migrations.AddField(
            model_name='course',
            name='course_time',
            field=models.TimeField(default=None),
        ),
        migrations.AlterField(
            model_name='course',
            name='course_img',
            field=models.ImageField(blank=True, upload_to='course_pics'),
        ),
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('parent_topics', models.ManyToManyField(blank=True, related_name='subtopics', to='course_app.topic')),
            ],
        ),
        migrations.AddField(
            model_name='course',
            name='topics',
            field=models.ManyToManyField(related_name='courses', to='course_app.topic'),
        ),
        migrations.DeleteModel(
            name='Topics',
        ),
    ]
